name: Deploy Alterações via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        server: ${{ secrets.FTP_HOST_BLOOMIN_PROJETOS }}
        username: ${{ secrets.FTP_USER_BLOOMIN_PROJETOS }}
        password: ${{ secrets.FTP_PASSWORD_BLOOMIN_PROJETOS }}
        remote-dir: /template-teste 

