name: Deploy Alterações via FTP

on:
  push:
    branches:
      - main

    workflow_dispatch: # Para rodar manualmente

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.FTP_HOST_BLOOMIN_PROJETOS }}
        username: ${{ secrets.FTP_USER_BLOOMIN_PROJETOS }}
        password: ${{ secrets.FTP_PASSWORD_BLOOMIN_PROJETOS }}
        server-dir: /template-teste-github/

